### ISSUE TITLE
Damage divised by 2

### ISSUE THREAD

**Issue by Niwareee** [Imanity-Software/iSpigot-Issues#2]
**Describe the bug**
With iSpigot the damage was divised by 2.
I compared the damage between iSpigot and PaperSpigot 1.8.8

With iSpigot:
https://media.discordapp.net/attachments/676825268761133065/678958640065019914/unknown.png

With PaperSpigot 1.8.8!
https://media.discordapp.net/attachments/676825268761133065/678958780343648266/unknown.png

**Desktop (please complete the following information):**
 - OS: [e.g. Linux ubuntu]
 - Version [e.g. 1.2.3]

**Full dump file (/iSpigot dump)**
iSpigot version=1.2.3
license server version=null
TPS=[20.0, 20.0, 20.0, 20.0]
Logic tick=226668.0
World tick=1.3294646E7
Late bind=false
OS=Linux
Java=1.8.0_212-8u212-b01-1~deb9u1-b01

World=Arenas
Chunks=10265
Entities=0
Players=0

World=practice
Chunks=541
Entities=5
Players=2

World=Arenas_2
Chunks=4640
Entities=0
Players=0

World=Arenas_1
Chunks=9940
Entities=0
Players=0

license_ssl_connection=true
auto_update=true
knockback_aliases=[kb]
weather_changes=false
use_higher_durability=false
use_playerdata=true
infinite_water=false
native_19_support=true
replace1_7title_as_chat=false
legacy_17_support=false
use_player_move_event=true
block_operations=true
do_chunk_unload=true
enable_mob_ai=true
disable_1_8entity_spawn_naturally=true
disable_1_8_stone_generation=false
tnt_optimization=false
optimizeLiquidExplosions=false
hide_tnt_entities=false
hide_falling_block_entities=false
pearl_taliban=false
pearl_through_fence_gate=false
pearl_through_tripwire=false
spawn_endermite=false
old_enchanting=false
show_hidden_player_in_tablist=false
integer_health_criteria=false
ping_command_enabled=true
cpu_information_in_tps=true
block_reload_command=true
cannon_break_obsidian=false
explode_break_blocks=true
explode_fast_block_breaking=true
showExplosionEffects=true
explode_optimized_typeA=true
explode_optimized_typeB=true
explode_optimized_typeC=true
explode_optimized_typeD=false
cannon_left_shooting=true
async_hit_detection=true
async_potion_movement=true
hit_detection_thread_type=SCHEDULED_EXECUTOR
potion_movement_thread_type=SCHEDULED_EXECUTOR
multiple_thread_world=false
world_thread_count=2
keep_alive_packet_frequency=40
restartType=RESTART
custom_plan_ping=null
custom_plan_ping_other=null
custom_plan_server_name=null
custom_plan_version=null
custom_plan_tps=null
custom_plan_tps_regular=null

Plugins:
  ViaVersion:
    Version: 2.2.3
    Author: [_MylesC, creeper123123321, Gerrygames, KennyTV, Matsv]
    Main: us.myles.ViaVersion.ViaVersionPlugin
    Enabled: true
  Citizens:
    Version: 2.0.16-SNAPSHOT (build 1267)
    Author: [aPunch, fullwall]
    Main: net.citizensnpcs.Citizens
    Enabled: true
  FastAsyncWorldEdit:
    Version: 19.05.02-d89cb44-1274-22.2.0
    Author: [Empire92]
    Main: com.boydti.fawe.bukkit.BukkitMain
    Enabled: true
  IPWhitelist:
    Version: 1.7
    Author: [roblabla]
    Main: net.craftminecraft.bukkit.ipwhitelist.IPWhitelist
    Enabled: true
  Practice:
    Version: 1.0
    Author: [Niware]
    Main: fr.niware.practice.Diver
    Enabled: true
  GroupManager:
    Version: 2.0 (2.11.1) (Phoenix)
    Author: [AnjoCaido, Gabriel Couto, ElgarL]
    Main: org.anjocaido.groupmanager.GroupManager
    Enabled: true
  AutoclickerVerif:
    Version: 1.0
    Author: [William]
    Main: fr.ctlserv.william.autoclick.Autoclick
    Enabled: true
  PlugMan:
    Version: 1.8.1
    Author: [ryanclancy000, ryanclancy000, jinks]
    Main: com.ryanclancy000.plugman.PlugMan
    Enabled: true
  CommandNPC:
    Version: 1.9.1
    Author: [messageofdeath]
    Main: me.messageofdeath.commandnpc.CommandNPC
    Enabled: true
  StrikePractice:
    Version: 2.9.1
    Author: [Toppe5]
    Main: ga.strikepractice.StrikePractice
    Enabled: true
  ProtocolLib:
    Version: 4.4.0
    Author: [dmulloy2, comphenix]
    Main: com.comphenix.protocol.ProtocolLib
    Enabled: true
  WorldEdit:
    Version: 6.1.9;caf0ad9
    Author: []
    Main: com.sk89q.worldedit.bukkit.WorldEditPlugin
    Enabled: true
  StrikeLeaderboards:
    Version: 1.1
    Author: [Toppe5]
    Main: ga.strikepractice.leaderboards.StrikeLeaderboards
    Enabled: true
  RoweFix:
    Version: 1.0
    Author: [Rowe]
    Main: rowe.rowefix.Main
    Enabled: true
...

**Comment by LeeGodSRC** [comment]
Hey, i tested both spigot and all the same

Paper:
![image](https://user-images.githubusercontent.com/36093806/74808300-1fbf2900-531d-11ea-8e48-7bf8c92f437a.png)

iSpigot:
![image](https://user-images.githubusercontent.com/36093806/74808441-6c0a6900-531d-11ea-995d-9865d9bd8a0f.png)

**Comment by LeeGodSRC** [comment]
solved
