### ISSUE TITLE
java.lang.RuntimeException: Already decorating

### ISSUE THREAD

**Issue by DasMaexle** [Imanity-Software/iSpigot-Issues#4]
**Describe the bug**
The server crashes after 150.000 error lines (after one player logged in)

**To Reproduce**
Can't really reproduce. Happened random when a player logged in.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Version 1.2.3

**Full dump file (/iSpigot dump)**
eg.
iSpigot version=1.2.3
license server version=null
TPS=[19.999784046331825, 19.99998510567776, 19.99999656760059, 19.99999893333339]
Logic tick=79794.0
World tick=6891867.0
Late bind=false
OS=Linux
Java=1.8.0_232-8u232-b09-1~deb9u1-b09

World=world
Chunks=2299
Entities=755
Players=24

World=world_the_end
Chunks=1
Entities=0
Players=0

World=world_nether
Chunks=289
Entities=13
Players=1

license_ssl_connection=true
auto_update=true
knockback_aliases=[kb]
weather_changes=true
use_higher_durability=false
use_playerdata=true
infinite_water=true
native_19_support=true
replace1_7title_as_chat=true
legacy_17_support=true
use_player_move_event=true
block_operations=true
do_chunk_unload=true
enable_mob_ai=true
disable_1_8entity_spawn_naturally=false
disable_1_8_stone_generation=false
tnt_optimization=true
optimizeLiquidExplosions=false
hide_tnt_entities=false
hide_falling_block_entities=false
pearl_taliban=false
pearl_through_fence_gate=false
pearl_through_tripwire=false
spawn_endermite=true
old_enchanting=false
show_hidden_player_in_tablist=false
integer_health_criteria=false
ping_command_enabled=true
cpu_information_in_tps=true
block_reload_command=true
cannon_break_obsidian=false
explode_break_blocks=true
explode_fast_block_breaking=true
showExplosionEffects=true
explode_optimized_typeA=true
explode_optimized_typeB=true
explode_optimized_typeC=true
explode_optimized_typeD=false
cannon_left_shooting=true
async_hit_detection=true
async_potion_movement=true
hit_detection_thread_type=SCHEDULED_EXECUTOR
potion_movement_thread_type=SCHEDULED_EXECUTOR
multiple_thread_world=true
world_thread_count=4
keep_alive_packet_frequency=40
restartType=STOP
custom_plan_ping=&7[&a*&7] &fYour ping is &a<ping>ms
custom_plan_ping_other=&7[&a*&7] &e<name>&f's ping is &a<ping>ms
custom_plan_server_name=iSpigot
custom_plan_version=[&7&m*-------------------------------*, &fThe server is currently running &eiSpigot, &fBased api version: &a1.8-R3, &fSpigot version: &a<version>, &7&m*-------------------------------*]
custom_plan_tps=[&7Server Statistics,   &7TPS&f <arrow> <tps5s>&a/20.0,   &7Server Lag&f &a<arrow> <lag>%,   &7Logic tick time&f <arrow> &a<logicTick>,   &7World tick time&f <arrow> &a<worldTick>,   &7Online&f <arrow> &a<online>/<maxOnline>,   &7Memory&f <arrow> &a<usedMemory>/<allocatedMemory> MB,   &7Uptime&f <arrow> &a<uptime>,   &7Entities&f <arrow> &a<entities>,   &7Chunks Loaded&f <arrow> &a<chunkLoaded> &7(<world>),   &7CPU Information,     &7Cores&f <arrow> &a<cpuCores>,     &7Cores&f <arrow> &a<cpuLoads>]
custom_plan_tps_regular=[&7&m*---------------------------------------------*, &fServer performance:&a <tps5s>&a/20.0, &fPerformance bar:&a <tpsBar>, &7&m*---------------------------------------------*]

Plugins:
  ViaVersion:
    Version: 2.2.3
    Author: [_MylesC, creeper123123321, Gerrygames, KennyTV, Matsv]
    Main: us.myles.ViaVersion.ViaVersionPlugin
    Enabled: true
  ViaRewind:
    Version: 1.4.4
    Author: [Gerrygames]
    Main: de.gerrygames.viarewind.BukkitPlugin
    Enabled: true
  AscalterAntiCrash:
    Version: 1.0.0
    Author: [DasMaexle]
    Main: de.ascalter.anticrash.AntiCrash
    Enabled: true
  FreebuildKit:
    Version: 0.0.1
    Author: [DasMaexle]
    Main: de.ascalter.kit.Kit
    Enabled: true
  World:
    Version: 1.0.0
    Author: [DasMaexle]
    Main: de.ascalter.world.World
    Enabled: true
  AntiLag:
    Version: 1.0.0
    Author: [DasMaexle]
    Main: de.ascalter.antilag.AntiLag
    Enabled: true
  PlugMan:
    Version: 2.1.6
    Author: [rylinaux]
    Main: com.rylinaux.plugman.PlugMan
    Enabled: true
  SpigotGuard:
    Version: 1.0-SNAPSHOT
    Author: [yooniks]
    Main: xyz.yooniks.spigotguard.SpigotGuardPlugin
    Enabled: true
  FarmLimiter:
    Version: 1.2
    Author: []
    Main: com.gmail.filoghost.farmlimiter.FarmLimiter
    Enabled: true
  ProtocolLib:
    Version: 4.5.0
    Author: [dmulloy2, comphenix]
    Main: com.comphenix.protocol.ProtocolLib
    Enabled: true
  Enchant:
    Version: 1.0
    Author: [TheKoopaCrafter]
    Main: ench.tkc.main.Main
    Enabled: true
  EntityDetection:
    Version: 1.1.3 (build #21)
    Author: [Phoenix616]
    Main: de.themoep.entitydetection.EntityDetection
    Enabled: true
  AscalterReward:
    Version: 1.0
    Author: [DoctorNieffer]
    Main: de.ascalter.reward.Reward
    Enabled: true
  FastAsyncWorldEdit:
    Version: 19.03.02-14f3b91-1254-22.0.11
    Author: [Empire92]
    Main: com.boydti.fawe.bukkit.BukkitMain
    Enabled: true
  AntiRedStoneCrash:
    Version: 1.0.0
    Author: [Lentry]
    Main: de.ascalter.antiredstone.AntiRedStone
    Enabled: true
  VoxelSniper:
    Version: 5.171.0-SNAPSHOT
    Author: [przerwap, MikeMatrix, Gavjenks, giltwist, psanker, Deamon5550, DivineRage]
    Main: com.thevoxelbox.voxelsniper.VoxelSniper
    Enabled: true
  Backpack:
    Version: 0.1
    Author: [Lentry]
    Main: de.ascalter.backpack.BackPack
    Enabled: true
  LabyModAPI:
    Version: 1.1
    Author: [LabyMedia]
    Main: net.labymod.serverapi.bukkit.LabyModPlugin
    Enabled: true
  Intave:
    Version: 13.0.4
    Author: [Jpx3, Malon1]
    Main: de.jpx3.intave.IntavePlugin
    Enabled: true
  API:
    Version: 1.3.0
    Author: [DasMaexle]
    Main: de.ascalter.api.API
    Enabled: true
  Warp:
    Version: 0.0.1
    Author: [DasMaexle]
    Main: de.ascalter.warp.Warp
    Enabled: true
  WorldEdit:
    Version: 6.1.9;caf0ad9
    Author: []
    Main: com.sk89q.worldedit.bukkit.WorldEditPlugin
    Enabled: true
  AntiDamageIndicator:
    Version: 1.0.0
    Author: [DasMaexle]
    Main: de.ascalter.antidamage.AntiDamageIndicator
    Enabled: true
  HolographicDisplays:
    Version: 2.4.1
    Author: []
    Main: com.gmail.filoghost.holographicdisplays.HolographicDisplays
    Enabled: true
  WorldGuard:
    Version: 6.1
    Author: []
    Main: com.sk89q.worldguard.bukkit.WorldGuardPlugin
    Enabled: true
  Freebuild:
    Version: 1.0.0
    Author: [DasMaexle]
    Main: de.ascalter.freebuild.Freebuild
    Enabled: true
  marry-system:
    Version: 1.1-SNAPSHOT
    Author: [RaiseException]
    Main: de.ascalter.marry.Marry
    Enabled: true
  WGRegionEvents:
    Version: 1.1
    Author: []
    Main: com.mewin.WGRegionEvents.WGRegionEventsPlugin
    Enabled: true
  Event:
    Version: 1.0.0
    Author: [DasMaexle]
    Main: de.ascalter.event.Event
    Enabled: true
  RedstoneClockPreventer:
    Version: 1.3.1
    Author: [MGbeenieboy]
    Main: me.craftwood.redstoneclockpreventer.Main
    Enabled: true

**Additional context**
Error log:
https://bin.ich-ha.be/up/2020-02-22-1.txt

**Comment by LeeGodSRC** [comment]
Might be fixed in next update
