### ISSUE TITLE
Saving inventory (playerdata) problem

### ISSUE THREAD

**Issue by bublif** [Imanity-Software/iSpigot-Issues#5]
So basically we are using Combattagplus, which spawns Combat Logger (NPC), when player leaves the game in combat. The npc wears players items etc. and when you kill him, it will drop player items and he will die when he joins back.  

But using iSpigot it doesn´t work (I can 100% assure you, it´s iSpigot thing, it works normal on default paperspigot).  When you kill NPC, items drop, but when he joins back, he joins with all the items. You can duplicate things.

**Comment by LeeGodSRC** [comment]
Please follow the template format.

**Comment by bublif** [comment]
**Describe the bug**
When you kill NPC, items drop, but when he joins back, he joins with all the items. You can duplicate things. Using iSpigot it doesn´t work (I can 100% assure you, it´s iSpigot thing, it works normal on default paperspigot). 

**To Reproduce**
When you kill NPC, items drop, but when he joins back, he joins with all the items. You can duplicate things.

**Expected behavior**
The npc wears players items etc. and when you kill him, it will drop player items and he will die when he joins back.

**Screenshots:**

Desktop (please complete the following information):

iSpigot version=1.2.3
license server version=null
TPS=[20.000235438771536, 20.000014730344184, 20.000003631267326, 20.000001476288997]
Logic tick=1783046.0
World tick=2770464.0
Late bind=false
OS=Linux
Java=1.8.0_242-8u242-b08-0ubuntu3~18.04-b08

World=test2
Chunks=256
Entities=68
Players=0

World=dung
Chunks=256
Entities=47
Players=0

World=Dungeonrunner
Chunks=256
Entities=27
Players=0

World=factions_the_end
Chunks=0
Entities=0
Players=0

World=test1
Chunks=256
Entities=43
Players=0

World=factions
Chunks=326
Entities=402
Players=2

World=factions_nether
Chunks=0
Entities=0
Players=0

license_ssl_connection=true
auto_update=true
knockback_aliases=[kb]
weather_changes=true
use_higher_durability=true
use_playerdata=true
infinite_water=true
native_19_support=true
replace1_7title_as_chat=true
legacy_17_support=true
use_player_move_event=true
block_operations=true
do_chunk_unload=true
enable_mob_ai=true
disable_1_8entity_spawn_naturally=true
disable_1_8_stone_generation=false
tnt_optimization=false
optimizeLiquidExplosions=false
hide_tnt_entities=false
hide_falling_block_entities=false
pearl_taliban=false
pearl_through_fence_gate=false
pearl_through_tripwire=true
spawn_endermite=true
old_enchanting=false
show_hidden_player_in_tablist=false
integer_health_criteria=false
ping_command_enabled=true
cpu_information_in_tps=true
block_reload_command=true
cannon_break_obsidian=false
explode_break_blocks=true
explode_fast_block_breaking=true
showExplosionEffects=true
explode_optimized_typeA=true
explode_optimized_typeB=true
explode_optimized_typeC=true
explode_optimized_typeD=false
cannon_left_shooting=true
async_hit_detection=true
async_potion_movement=true
hit_detection_thread_type=SCHEDULED_EXECUTOR
potion_movement_thread_type=SCHEDULED_EXECUTOR
multiple_thread_world=false
world_thread_count=2
keep_alive_packet_frequency=40
restartType=STOP
custom_plan_ping=null
custom_plan_ping_other=null
custom_plan_server_name=null
custom_plan_version=null
custom_plan_tps=null
custom_plan_tps_regular=null

**Plugins:**
I can share plugins only privately, but I assure you it has nothing to do with plugins, since the same settings works perfectly with normal paperspigot.

  CombatTagPlus:
    Version: 1.3.1
    Author: [Byteflux, Sudzzy]
    Main: net.minelink.ctplus.CombatTagPlus
    Enabled: true

**Comment by LeeGodSRC** [comment]
Solved
