### ISSUE TITLE
PlotSquared change biome

### ISSUE THREAD

**Issue by DasMaexle** [Imanity-Software/iSpigot-Issues#6]
**Describe the bug**
When i want to change biome with Plotsquared (/p biome <biome>) it will not work and all players in the chunk get kicked.

**To Reproduce**
You need PlotSquared and execute the command "/plot biome jungle" as a player on a plot (with a big merge or just a big radius). In a plot with around 20x20 blocks it will work because the plot is not big enough. I am pretty sure i has something to do with new chunk generation.

**Expected behavior**
All players in the chunk get kicked, the biome will not change and in console just "java.lang.NullPointerException" spamming.

**Screenshots**
https://prnt.sc/rd0ldy

**Desktop (please complete the following information):**
 - Debian 10
 - Version 1.3b2-BETA

**Full dump file (/iSpigot dump)**
iSpigot version=1.3-BETA
license server version=null
TPS=[19.999932316229057, 20.970792164094107, 20.57111556596556, 20.1868154155949]
Logic tick=524033.0
World tick=4122169.0
Late bind=false
OS=Linux
Java=1.8.0_211-b12

World=world
Chunks=256
Entities=25
Players=0

World=world_the_end
Chunks=0
Entities=0
Players=0

World=world_nether
Chunks=0
Entities=0
Players=0

World=plotworld
Chunks=611
Entities=322
Players=3

World=farmwelt
Chunks=545
Entities=115
Players=1

knockback_aliases=[kb]
weather_changes=true
use_higher_durability=false
use_playerdata=true
infinite_water=true
native_19_support=true
replace1_7title_as_chat=true
legacy_17_support=true
reference_count_fix=false
use_player_move_event=true
block_operations=true
do_chunk_unload=true
enable_mob_ai=true
disable_1_8entity_spawn_naturally=false
disable_1_8_stone_generation=false
tnt_optimization=true
optimizeLiquidExplosions=false
hide_tnt_entities=false
hide_falling_block_entities=false
pearl_taliban=false
pearl_through_fence_gate=false
pearl_through_tripwire=false
spawn_endermite=true
old_enchanting=false
show_hidden_player_in_tablist=false
integer_health_criteria=false
ping_command_enabled=true
cpu_information_in_tps=true
block_reload_command=true
cannon_break_obsidian=false
explode_break_blocks=true
explode_fast_block_breaking=true
showExplosionEffects=true
explode_optimized_typeA=true
explode_optimized_typeB=true
explode_optimized_typeC=true
explode_optimized_typeD=false
cannon_left_shooting=true
async_hit_detection=true
async_potion_movement=true
async_entity_tracking=true
async_entities_ticking=false
hit_detection_thread_type=SCHEDULED_EXECUTOR
potion_movement_thread_type=SCHEDULED_EXECUTOR
multiple_thread_world=true
keep_alive_packet_frequency=40
custom_plan_ping=&7[&a*&7] &fYour ping is &a<ping>ms
custom_plan_ping_other=&7[&a*&7] &e<name>&f's ping is &a<ping>ms
custom_plan_server_name=iSpigot
custom_plan_version=[&7&m*-------------------------------*, &fThe server is currently running &eiSpigot, &fBased api version: &a1.8-R3, &fSpigot version: &a<version>, &7&m*-------------------------------*]
custom_plan_tps=[&7Server Statistics,   &7TPS&f <arrow> <tps5s>&a/20.0,   &7Server Lag&f &a<arrow> <lag>%,   &7Logic tick time&f <arrow> &a<logicTick>,   &7World tick time&f <arrow> &a<worldTick>,   &7Online&f <arrow> &a<online>/<maxOnline>,   &7Memory&f <arrow> &a<usedMemory>/<allocatedMemory> MB,   &7Uptime&f <arrow> &a<uptime>,   &7Entities&f <arrow> &a<entities>,   &7Chunks Loaded&f <arrow> &a<chunkLoaded> &7(<world>),   &7CPU Information,     &7Cores&f <arrow> &a<cpuCores>,     &7Cores&f <arrow> &a<cpuLoads>]
custom_plan_tps_regular=[&7&m*---------------------------------------------*, &fServer performance:&a <tps5s>&a/20.0, &fPerformance bar:&a <tpsBar>, &7&m*---------------------------------------------*]

Plugins:
  ViaVersion:
    Version: 2.2.3
    Author: [_MylesC, creeper123123321, Gerrygames, KennyTV, Matsv]
    Main: us.myles.ViaVersion.ViaVersionPlugin
    Enabled: true
  ViaRewind:
    Version: 1.4.4
    Author: [Gerrygames]
    Main: de.gerrygames.viarewind.BukkitPlugin
    Enabled: true
  FastAsyncWorldEdit:
    Version: 19.03.02-14f3b91-1254-22.0.11
    Author: [Empire92]
    Main: com.boydti.fawe.bukkit.BukkitMain
    Enabled: true
  AntiRedStoneCrash:
    Version: 1.0.0
    Author: [Lentry]
    Main: de.ascalter.antiredstone.AntiRedStone
    Enabled: true
  World:
    Version: 1.0.0
    Author: [DasMaexle]
    Main: de.ascalter.world.World
    Enabled: true
  ClearLag:
    Version: 3.1.6
    Author: [bob7l]
    Main: me.minebuilders.clearlag.Clearlag
    Enabled: true
  PlugMan:
    Version: 2.0.8
    Author: [rylinaux]
    Main: com.rylinaux.plugman.PlugMan
    Enabled: true
  SpigotGuard:
    Version: 2.7-SNAPSHOT
    Author: [yooniks]
    Main: xyz.yooniks.spigotguard.SpigotGuardPlugin
    Enabled: true
  LabyModAPI:
    Version: 1.1
    Author: [LabyMedia]
    Main: net.labymod.serverapi.bukkit.LabyModPlugin
    Enabled: true
  ArmorStandCrashFix:
    Version: 1.0.4
    Author: [JoeyPlayzTV]
    Main: de.joeyplayztv.armorstandcrashfix.ArmorStandCrashFix
    Enabled: true
  API:
    Version: 1.3.0
    Author: [DasMaexle]
    Main: de.ascalter.api.API
    Enabled: true
  ProtocolLib:
    Version: 4.4.0
    Author: [dmulloy2, comphenix]
    Main: com.comphenix.protocol.ProtocolLib
    Enabled: true
  Warp:
    Version: 0.0.1
    Author: [DasMaexle]
    Main: de.ascalter.warp.Warp
    Enabled: true
  WorldEdit:
    Version: 6.1.9;caf0ad9
    Author: []
    Main: com.sk89q.worldedit.bukkit.WorldEditPlugin
    Enabled: true
  AscalterAntiCrash:
    Version: 1.1.3
    Author: [DasMaexle]
    Main: de.ascalter.anticrash.AntiCrash
    Enabled: true
  CityBuild:
    Version: 1.0.0
    Author: [DasMaexle]
    Main: de.ascalter.citybuild.Citybuild
    Enabled: true
  marry-system:
    Version: 1.1-SNAPSHOT
    Author: [RaiseException]
    Main: de.ascalter.marry.Marry
    Enabled: true
  Intave:
    Version: 13.0.4
    Author: [Jpx3, Malon1]
    Main: de.jpx3.intave.IntavePlugin
    Enabled: true
  AntiDamageIndicator:
    Version: 1.0.0
    Author: [DasMaexle]
    Main: de.ascalter.antidamage.AntiDamageIndicator
    Enabled: true
  HolographicDisplays:
    Version: 2.4.1
    Author: []
    Main: com.gmail.filoghost.holographicdisplays.HolographicDisplays
    Enabled: true
  PlotSquared:
    Version: 19.07.13-44ad99e-773
    Author: [Citymonstret, Empire92, MattBDev, dordsor21]
    Main: com.plotsquared.bukkit.BukkitMain
    Enabled: true
  WorldGuard:
    Version: 6.1
    Author: []
    Main: com.sk89q.worldguard.bukkit.WorldGuardPlugin
    Enabled: true

**Additional context**

**Comment by LeeGodSRC** [comment]
Solved
